#!/usr/bin/env python3
"""Generate golden_vectors.json + golden_vectors.c from the same
python reference used in Phase 5 (`kquity_pressure_ref.py`).

Output:
  tests/golden_vectors.json   list of {features, logit, prob}
  tests/golden_vectors.c       static const C arrays for test_native.c

Bit-exact to Phase 5. 128 random pool draws + 24 endpoint clamp
probes = 152 vectors, same construction as
experiments/kquity_hw/hls/gen_golden.py.
"""
from __future__ import annotations

import argparse
import glob
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
HLS_DIR = REPO / "experiments/kquity_hw/hls"
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(HLS_DIR))

import fast_materialize as fm  # noqa: E402
import kquity_pressure_ref as ref  # noqa: E402


def diffs(X):
    egg = X[:, 0] - X[:, 20]
    food = X[:, 1] - X[:, 21]
    snail = X[:, 49]
    sol = X[:, 3] - X[:, 23]
    war = X[:, 2] - X[:, 22]
    ber = X[:, 51]
    return np.column_stack([egg, food, snail, sol, war, ber]).astype(np.float64)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--phase4-json",
        default=str(REPO / "experiments/kquity_hw/results/phase4_fixed_point.json"),
    )
    ap.add_argument(
        "--csv-glob",
        default=str(REPO / "tests/benchmark_events_*.csv.gz"),
    )
    ap.add_argument("--n", type=int, default=128)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--out-json", default=str(HERE / "golden_vectors.json"))
    ap.add_argument("--out-c", default=str(HERE / "golden_vectors.c"))
    args = ap.parse_args()

    consts = ref.make_constants(
        *(lambda j: (j["float_weights"], j["float_intercept"]))(
            json.loads(Path(args.phase4_json).read_text())
        )
    )

    paths = sorted(glob.glob(args.csv_glob))
    if not paths:
        raise FileNotFoundError(args.csv_glob)
    res = fm.fast_materialize(paths[0], drop_state_probability=0.0)
    X = res[0]
    D = diffs(X)
    rng = np.random.RandomState(args.seed)
    idx = rng.choice(len(D), size=min(args.n, len(D)), replace=False)
    D_sample = D[idx]

    edge_rows = []
    for nm in ref.DIFF_NAMES:
        norm = ref.FEATURE_NORM[nm]
        for v in (
            norm["center"] - norm["half_range"],
            norm["center"] + norm["half_range"],
            norm["center"] + 1e9,
            norm["center"] - 1e9,
        ):
            row = []
            for nm2 in ref.DIFF_NAMES:
                row.append(v if nm2 == nm else ref.FEATURE_NORM[nm2]["center"])
            edge_rows.append(np.array(row, dtype=np.float64))
    edge_rows = np.array(edge_rows)

    D_all = np.concatenate([D_sample, edge_rows])
    n = D_all.shape[0]
    x_int = ref.quantize_features_int8(D_all)
    acc = ref.kquity_logit_q8(x_int, consts["w_int"], consts["b_acc"])
    logit = ref.saturate_int16(acc)
    lut = ref.build_sigmoid_lut()
    prob = ref.kquity_prob_lut(logit, lut)

    # JSON
    records = []
    for i in range(n):
        records.append(
            {
                "features": [int(v) for v in x_int[i]],
                "logit": int(logit[i]),
                "prob": int(prob[i]),
            }
        )
    json_obj = {
        "n_vectors": n,
        "n_random": int(args.n),
        "n_edge_probes": int(len(edge_rows)),
        "feature_order": ref.DIFF_NAMES,
        "logit_q_format": "Q4.12 (signed int16)",
        "prob_format": "uint16 (sigmoid * 65535)",
        "records": records,
    }
    Path(args.out_json).write_text(json.dumps(json_obj, indent=2))
    print(f"wrote {args.out_json}  ({n} vectors)")

    # C array for native test
    lines = []
    lines.append("// SPDX-License-Identifier: MIT")
    lines.append("// Generated by tests/gen_golden_json.py")
    lines.append("// Bit-exact against kquity_pressure_ref.py.")
    lines.append("// Do not edit by hand.")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"const int kquity_golden_n = {n};")
    lines.append("")
    lines.append(f"const int8_t kquity_golden_x[{n}][6] = {{")
    for i in range(n):
        row = ", ".join(f"{int(v):>4d}" for v in x_int[i])
        comma = "," if i < n - 1 else ""
        lines.append(f"    {{ {row} }}{comma}")
    lines.append("};")
    lines.append("")
    lines.append(f"const int16_t kquity_golden_logit[{n}] = {{")
    for i in range(0, n, 8):
        s = ", ".join(f"{int(v):>6d}" for v in logit[i : i + 8])
        comma = "," if i + 8 < n else ""
        lines.append(f"    {s}{comma}")
    lines.append("};")
    lines.append("")
    lines.append(f"const uint16_t kquity_golden_prob[{n}] = {{")
    for i in range(0, n, 8):
        s = ", ".join(f"{int(v):>5d}" for v in prob[i : i + 8])
        comma = "," if i + 8 < n else ""
        lines.append(f"    {s}{comma}")
    lines.append("};")
    lines.append("")
    Path(args.out_c).write_text("\n".join(lines))
    print(f"wrote {args.out_c}")


if __name__ == "__main__":
    main()
